Repository ekreative/react-native-braintree, pull requests merged in 2023-10, with the labels that each got.

#62 Add prettier
  .prettierignore
  .prettierrc.js
  index.d.ts
  index.js
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#65 Add eslint
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#47 CI/CD-template-added
  .github/workflows/npm-publish.yml
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#64 add useful links and resources section in README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#69 build: update setup-node action, node versions, enable cache
  .github/workflows/lint.yml
  .github/workflows/npm-publish.yml
Labels: hacktoberfest, hacktoberfest-accepted

#71 build: remove unsupported cache option
  .github/workflows/lint.yml
  .github/workflows/npm-publish.yml
Labels: hacktoberfest, hacktoberfest-accepted

#77 Branch name linter
  branch-name-lint.config.js
  package-lock.json
  package.json
Labels: hacktoberfest, beginner, hacktoberfest-accepted

#81 bugs: solved linting error
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#79 fix: config for Prettier formatter
  .prettierignore
  branch-name-lint.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#78 Add Guide on how to migrate code from Objective-C to Swift
  docs/migration-objc-to-swift-guide.md
Labels: hacktoberfest, advanced, hacktoberfest-accepted

#80 Add npm,release, native SDK version in README.md
  README.md
Labels: hacktoberfest, beginner, hacktoberfest-accepted
